#!/usr/bin/env bash

current_dir=${PWD}

if [ ! -d "~/.config/fish/functions/" ]; then
    mkdir -p ~/.config/fish/functions
fi

echo "Cleaning old files"
rm -f ~/.zshrc
rm -f ~/.vimrc
rm -f ~/.gitconfig
rm -f ~/.oh-my-zsh/themes/mytheme.zsh-theme
rm -f ~/.config/fish/config.fish

echo "Linking files"
ln -s $current_dir/zshrc		~/.zshrc
ln -s $current_dir/vimrc		~/.vimrc
ln -s $current_dir/gitconfig		~/.gitconfig
ln -s $current_dir/mytheme.zsh-theme	~/.oh-my-zsh/themes/mytheme.zsh-theme
ln -s $current_dir/config.fish     ~/.config/fish/config.fish

echo "Fuck Yeahhh!"
